name: Deploy docs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material
          pip install markdown-extensions pymdown-extensions

      - name: Deploy docs
        run: |
          mkdocs gh-deploy --config-file mkdocs.yml \
                           --remote-branch gh-pages \
                           --theme-material \
                           --markdown-extension=pymdownx.superfences \
                           --markdown-extension=tables \
                           --markdown-extension=pymdownx.highlight:
                               anchor_linenums: true \
                           --markdown-extension=pymdownx.inlinehilite \
                           --markdown-extension=pymdownx.snippets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}